// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yytspocfzrtpbmhshrck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5dHNwb2NmenJ0cGJtaHNocmNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwNTg3MjMsImV4cCI6MjA2MTYzNDcyM30.tMI8SHfno7B-j5ruPXSYbGigUpMLAQa6gw8tiOYv1aI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);